#!/bin/bash

echo -e "${s_text}${s_back}HOSTNAME${THE_END} = ${f_text}${f_back}$HOSTNAME${THE_END}"
echo -e "${s_text}${s_back}TIMEZONE${THE_END} = ${f_text}${f_back}$TIMEZONE${THE_END}"
echo -e "${s_text}${s_back}USER${THE_END} = ${f_text}${f_back}$USER${THE_END}"
echo -e "${s_text}${s_back}OS${THE_END} = ${f_text}${f_back}$OS${THE_END}"
echo -e "${s_text}${s_back}DATE${THE_END} = ${f_text}${f_back}$DATE${THE_END}"
echo -e "${s_text}${s_back}UPTIME${THE_END} = ${f_text}${f_back}$UPTIME${THE_END}"
echo -e "${s_text}${s_back}UPTIME_SEC${THE_END} = ${f_text}${f_back}$UPTIME_SEC${THE_END}"
echo -e "${s_text}${s_back}IP${THE_END} = ${f_text}${f_back}$IP${THE_END}"
echo -e "${s_text}${s_back}MASK${THE_END} = ${f_text}${f_back}$MASK${THE_END}"
echo -e "${s_text}${s_back}GATEWAY${THE_END} = ${f_text}${f_back}$GATEWAY${THE_END}"
echo -e "${s_text}${s_back}RAM_TOTAL${THE_END} = ${f_text}${f_back}$RAM_TOTAL${THE_END}"
echo -e "${s_text}${s_back}RAM_USED${THE_END} = ${f_text}${f_back}$RAM_USED${THE_END}"
echo -e "${s_text}${s_back}RAM_FREE${THE_END} = ${f_text}${f_back}$RAM_FREE${THE_END}"
echo -e "${s_text}${s_back}SPACE_ROOT${THE_END} = ${f_text}${f_back}$SPACE_ROOT${THE_END}"
echo -e "${s_text}${s_back}SPACE_ROOT_USED${THE_END} = ${f_text}${f_back}$SPACE_ROOT_USED${THE_END}"
echo -e "${s_text}${s_back}SPACE_ROOT_FREE${THE_END} = ${f_text}${f_back}$SPACE_ROOT_FREE${THE_END}"
